### ISSUE TITLE
Ability to move scaled down image

### ISSUE THREAD

**Issue by stepanov-standy** [bluefireteam/photo_view#334]
**Is your feature request related to a problem? Please describe.**
PhotoView allows to scale down image and its very useful. But unfortunately scaled down image can be only rotated. It is not possible to move it to change its position. Current implementation supports move only on zoomed image.

**Describe the solution you'd like**
Support an ability to move scaled down image.

**Comment by MohdFaizan123** [comment]
I would also want to have this please.

**Comment by Aerofluxx** [comment]
Yes I'm also into this. 👍

**Comment by suneeltechnew** [comment]
I am also looking for this...

**Comment by stepanov-standy** [comment]
Hi Folks, looks like our problem was solved back to July 2021 :) When a new property enablePanAlways: true was added in the release 0.12.0!

Now we can rotate and move the image even when it is downscaled 👍 

Closing this feature request as implemented. Well done!
