### ISSUE TITLE
Dismiss Image when using Hero

### ISSUE THREAD

**Issue by Urkman** [bluefireteam/photo_view#408]
I used you Hero example in my App. This works fine, but I can't dismiss the image on iOS...
Is there a way to support a down swipe to dismiss the image? Like Facebook or Twitter?

**Comment by Urkman** [comment]
OK, found some entries... As there will be no solution for it, I need to look for an other package.
Any suggestions?

**Comment by renancaraujo** [comment]
Have you seen the [integration with dialogs in the example app](https://github.com/fireslime/photo_view/blob/master/example/lib/screens/examples/dialog_example.dart)?

**Comment by jinfagang** [comment]
@Urkman Got same issue, is there a clean way to do it on iOS? Such as make SwipDown gesture or something?

**Comment by Urkman** [comment]
I'm still looking for alternativ solution... The Hero Animation also looks bad on iOS...

**Comment by jinfagang** [comment]
@Urkman It seems very limited alternatives on flutter community which can achieve hero transition and photo preview. This libs have many stars I thought it could be mature but it can not even handle this tiny basic function on iOS.

**Comment by renancaraujo** [comment]
This issue doednt provide anydetails on how to fix that problem and if you have a little undertanding on how flutter works you will know that this lib doensnt implement hero neither any platform specific code. 

@ jinfagang  It is open source, "community" is not only deminding people to fill your own necessities. It means healping to investigate and solve problems as well.

**Comment by Urkman** [comment]
@jinfagang Here is a gist, that I currently use. I put some things together, to get it working on iOS and Android...
[https://gist.github.com/Urkman/e765f5270c357f8f9d1f703d439d88c1](url)

Let me know, if it works for you...
