### ISSUE TITLE
errorBuilder attribute of PhotoView NOT WORKING

### ISSUE THREAD

**Issue by kamleshwebtech** [bluefireteam/photo_view#430]
I have used errorBuilder attribute of PhotoView:

```
PhotoView(
  imageProvider: NetworkImage(
    widget.photoPath.toString(),
  ),
  errorBuilder: (BuildContext context, Object exception, StackTrace stackTrace) { 
    return Scaffold(
      body: Center(
        child: Text('Photo is not available, please try later.'),
      ),
    );
  },
)
```

Kindly tell me what is wrong with it and how can we solve it. Thanks.

**Comment by kamleshwebtech** [comment]
@renancaraujo  @Carlit0 @SocratesDz @AlexVegner @memo4mj  Please share your suggestion on this issue. Thanks.

**Comment by FaKenKoala** [comment]
@kamleshwebtech If you set an error path, it works. Is it maybe your network issue, like not yet fetch result because of waiting too long ?
