### ISSUE TITLE
Can i use custom child to play videos?

### ISSUE THREAD

**Issue by lucasdidur** [bluefireteam/photo_view#448]
I want to create a gallery to show all files inside of a folder. So there is videos and images.

Can i use custom child to play videos? If so, how do i do?

**Comment by renancaraujo** [comment]
I have no idea.

**Comment by JRochaTractian** [comment]
Same problem here

**Comment by zoy-l** [comment]
hack: errorBuilder :)

**Comment by kevin4dhd** [comment]
any example please?
