### ISSUE TITLE
Hi I'd like to implement the close image gesture.

### ISSUE THREAD

**Issue by Ahtram** [bluefireteam/photo_view#449]
Hi, 
Thank you for the great package!
I'd like to implement the gesture close image viewer feature.

For example:
![20210729_214320](https://user-images.githubusercontent.com/1751201/127502860-09142724-76a1-4fc7-924a-ecd53403a27f.gif)

To achieve this, I need to get a notify if the viewing image is offsetted overbound. 
Or I guess expose the current viewing image's current offset by callback should make this possible.

Thank you!

**Comment by mark8044** [comment]
This looks amazing!
Let us know if you make progress with this idea

**Comment by guotao** [comment]
I want this too。。。

**Comment by renancaraujo** [comment]
Wow, you will need some deep flutter skills to do this. Maybe combining `GestureDetecetctor` + `PhotoView` + `ModalRoute`?

**Comment by renancaraujo** [comment]
Since this is not a bug report nor a specific feature request, we can follow-up on this on discord.
