### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by libaipengl** [bluefireteam/photo_view#456]
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"

            child: Container(
                child: PhotoViewGallery.builder(
              scrollPhysics: const BouncingScrollPhysics(),
              builder: (BuildContext context, int index) {
                return PhotoViewGalleryPageOptions(
                    filterQuality:FilterQuality.low,
                   imageProvider: NetworkImage(widget.images[index]),
                  //imageProvider: AssetImage('assets/images/bg.jpg'),
                  heroAttributes: widget.heroTag.isNotEmpty
                      ? PhotoViewHeroAttributes(tag: widget.heroTag)
                      : null,
                );
              },
              itemCount: widget.images.length,
              // loadingChild: Container(),
              backgroundDecoration: null,
              pageController: widget.controller,
              enableRotation: true,
              onPageChanged: (index) {
                setState(() {
                  currentIndex = index;
                });
              },
            )),

1、NetworkImage   Network pictures are not displayed
2、Does it support image blur and long press

**Comment by renancaraujo** [comment]
TRacking network errors on #464.

>  2、Does it support image blur and long press
I don't know what you mean. Can you elaborate more on an issue following the template?
https://github.com/bluefireteam/photo_view/issues/new?assignees=&labels=&template=feature_request.md&title=
