### ISSUE TITLE
Resolving white flashes when performing quick scroll by adding allowImplicitScrolling: true to Page View

### ISSUE THREAD

**Issue by zixuan-espressoft** [bluefireteam/photo_view#457]
I found a solution to prevent the white flashes when having a quick scroll on PageView.

on PageView, there's a allowImplicitScrolling parameter, I hope you could add it to PhotoViewGallery.builder.
Reference: https://stackoverflow.com/questions/50663074/preload-network-images-using-pageview

Suggestion: add **allowImplicitScrolling** as a parameter to PhotoViewGallery.builder.

Thanks!!!

**Comment by renancaraujo** [comment]
That was added o 0.13.0.
