### ISSUE TITLE
[BUG]not working for NetworkImage in flutter 2.5

### ISSUE THREAD

**Issue by buimanhhungit** [bluefireteam/photo_view#464]
`PhotoView(imageProvider: NetworkImage(link,),)` not working in flutter 2.5

**Comment by mustafa-707** [comment]
same here when upgrade to
` flutter 2.5.0 `
the NetworkImage in preview is broken

**Comment by renancaraujo** [comment]
on it

**Comment by renancaraujo** [comment]
The fix is now published on 0.13.0
