### ISSUE TITLE
APP_NAME depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed

### ISSUE THREAD

**Issue by bipindubey-technoark** [bluefireteam/photo_view#466]
I am getting this issue while running the flutter pub get.
I am not able to build an android apk.

`Because native_pdf_view 4.1.0 depends on photo_view ^0.11.1 and no versions of native_pdf_view match >4.1.0 <5.0.0, native_pdf_view ^4.1.0 requires photo_view ^0.11.1. So, because flutter_funds_app depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed. pub get failed (1; So, because flutter_funds_app depends on both native_pdf_view ^4.1.0 and photo_view ^0.12.0, version solving failed.)
`
Thanks

**Comment by renancaraujo** [comment]
That is because native_pdf_view is using an outdated version of photo view. You can use dependency overrides.

**Comment by bipindubey-technoark** [comment]
> That is because native_pdf_view is using an outdated version of photo view. You can use dependency overrides.

how to use dependency overrides??

i have found 1 solution but i am not happy with it
i put any as version in photo view  it works but it takes 0.11.1 i think to solve the issue 
i want 0.12.0 

@renancaraujo

**Comment by renancaraujo** [comment]
https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by renancaraujo** [comment]
Just put this in your pubspec.
```
dependency_overrides:
  photo_view: 0.12.0
```

**Comment by renancaraujo** [comment]
https://github.com/bluefireteam/photo_view/issues/459#issuecomment-921678753
