### ISSUE TITLE
Waiting for new release with Flutter 2.10.x

### ISSUE THREAD

**Issue by saelco** [bluefireteam/photo_view#505]
Error "Looking up a deactivated widget's ancestor is unsafe." fixed by https://github.com/bluefireteam/photo_view/pull/499, but I'm still waiting for new release.

**Comment by alymbouras** [comment]
I have spent lots of hours trying to understand where the error was coming from. 
My whole page was being deactivated causing all sorts of different errors.

I eventually ended up using the code from master on my pubspec.yaml:

  photo_view:
    git: https://github.com/bluefireteam/photo_view.git

**Comment by michealch** [comment]
I too waisted lots of hours too. XD

Going back to flutter 2.8.1 fix the problem

**Comment by Christyansoft** [comment]
@Chamed  i'm using this solution: https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe/71010204#71010204

**Comment by whquddn55** [comment]
> @Chamed i'm using this solution: https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe/71010204#71010204

OMG.... I have revised my codes to fix this bug almost 2 days.... 
This solution works perfectly to me!!! thx :)

**Comment by tomaspodmanicky** [comment]
When can we expect fix for this error? I don't want to downgrade Flutter because of this.

**Comment by JamesMcIntosh** [comment]
@renancaraujo are you able to publish a release with the updated fixes as it's been in master for over a week?

**Comment by Arcturus5404** [comment]
Also spend some time debugging this. It also gave a problem with a globalkey on the photoview; not sure if it is related, but I think so, because the controller would still be alive when switching pages.

Anyway, I am now on the master branch in my pubspec.yml

```
photo_view:
   git: https://github.com/bluefireteam/photo_view.git
```

**Comment by kamilpowalowski** [comment]
@bluefireteam @renancaraujo Any update on this one?

**Comment by michealch** [comment]
@LarssK-TS it seems like

**Comment by renancaraujo** [comment]
Doing a release ASAP, sorry for the huge delay.

**Comment by LarssK-TS** [comment]
> Doing a release ASAP, sorry for the huge delay.

thank you, much appreciated!

**Comment by renancaraujo** [comment]
Done, 0.14.0 is out. Sorry again
