### ISSUE TITLE
Uncaught Exception [BUG]

### ISSUE THREAD

**Issue by 3990995** [bluefireteam/photo_view#512]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:4182
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:4196
#2      Element.getElementForInheritedWidgetOfExactType
package:flutter/…/widgets/framework.dart:4227
#3      TickerMode.getNotifier
package:flutter/…/widgets/ticker_provider.dart:95
#4      TickerProviderStateMixin._updateTickerModeNotifier
package:flutter/…/widgets/ticker_provider.dart:324
#5      TickerProviderStateMixin.createTicker
package:flutter/…/widgets/ticker_provider.dart:288
#6      new AnimationController
package:flutter/…/animation/animation_controller.dart:246
#7      PhotoViewCoreState._scaleAnimationController
package:photo_view/…/core/photo_view_core.dart:112
#8      PhotoViewCoreState._scaleAnimationController (package:photo_view/src/core/photo_view_core.dart)
package:photo_view/…/core/photo_view_core.dart:1
#9      PhotoViewCoreState.dispose
package:photo_view/…/core/photo_view_core.dart:274

**Comment by 3990995** [comment]
`showDialog(
                  context: context,
                  builder: (BuildContext context) {
                    return BackdropFilter(
                      filter: ImageFilter.blur(sigmaX: 6.0, sigmaY: 6.0),
                      child: Dialog(
                        backgroundColor: Colors.transparent,
                        child: PhotoView(
                          minScale: PhotoViewComputedScale.contained * 0.8,
                          maxScale: PhotoViewComputedScale.covered * 1.8,
                          initialScale: PhotoViewComputedScale.contained,
                          backgroundDecoration:
                              const BoxDecoration(color: Colors.transparent),
                          heroAttributes:
                              PhotoViewHeroAttributes(tag: "img_$index"),
                          tightMode: true,
                          imageProvider:
                              AssetImage("assets/questions/" + image),
                        ),
                      ),
                    );
                  },
                );`

**Comment by Moyout** [comment]
Also encountered problems

**Comment by renancaraujo** [comment]
May be fixed on 0.14.0. See #505
