### ISSUE TITLE
[BUG] How to solve it?

### ISSUE THREAD

**Issue by keyes2003** [bluefireteam/photo_view#513]
`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:photo_view/photo_view.dart';
import 'package:photo_view/photo_view_gallery.dart';

import 'image_preview_logic.dart';

class ImagePreviewPage extends StatelessWidget {
  ImagePreviewPage({Key? key}) : super(key: key);
  final logic = Get.find<ImagePreviewLogic>();

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      child: Obx(
        () => PhotoViewGallery.builder(
          itemCount: logic.images.value.length,
          scrollPhysics: const BouncingScrollPhysics(),
          pageController: PageController(),
          builder: (context, idx) => PhotoViewGalleryPageOptions(
            imageProvider: NetworkImage(logic.images.value[idx]['file_url']),
            initialScale: PhotoViewComputedScale.contained * 0.8,
            heroAttributes: PhotoViewHeroAttributes(tag: logic.images.value[idx]['file_id']),
          ),
          loadingBuilder: (context, event) => Center(
            child: SizedBox(
              width: 40.w,
              height: 40.h,
              child: CircularProgressIndicator(
                value: event == null ? 0 : event.cumulativeBytesLoaded / event.expectedTotalBytes!,
              ),
            ),
          ),
        ),
      ),
    );
  }
}`

I/flutter (15623): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (15623): The following assertion was thrown while finalizing the widget tree:
I/flutter (15623): Looking up a deactivated widget's ancestor is unsafe.
I/flutter (15623): At this point the state of the widget's element tree is no longer stable.
I/flutter (15623): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
I/flutter (15623): calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by renancaraujo** [comment]
May be fixed on 0.14.0. See #505

**Comment by keyes2003** [comment]
HELLO 
      我已收到您的来信，我会及时回复邮件。
